name: baidu_speech_recognition_example
description: Demonstrates how to use the baidu_speech_recognition plugin.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  baidu_speech_recognition:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/meter_level_0.png
    - assets/images/meter_level_1.png
    - assets/images/meter_level_2.png
    - assets/images/meter_level_3.png
    - assets/images/meter_level_4.png
    - assets/images/meter_level_5.png
    - assets/images/meter_level_6.png
    - assets/audio/off.mp3
    - assets/audio/on.mp3
